services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data      
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    environment:
      - ELASTICSEARCH_HOST=elasticsearch        
    ports:
      - "5044:5044"
      - "9600:9600"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]  
    volumes:   
      - ./data/logstash:/usr/share/logstash/data  
      - ./certs:/usr/share/elasticsearch/config/certs
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch  
      - XPACK_ENCRYPTION_KEY=${XPACK_ENCRYPTION_KEY}      
      - ELASTICSEARCH_USERNAME=${KIBANA_SYSTEM_USERNAME}            
      - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_PASSWORD}
      # - SERVER_SSL_ENABLED=true
      # - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/kibana.crt
      # - SERVER_SSL_KEY=/usr/share/kibana/config/certs/kibana.key
    # depends_on:
      # elasticsearch:
      #   condition: service_healthy     
    volumes:
      - ./data/kibana:/usr/share/kibana/data 
      # - ./certs:/usr/share/kibana/config/certs
      

  fleet-server:
    image: docker.elastic.co/beats/elastic-agent:8.10.1
    container_name: fleet-server
    environment:
      - FLEET_SERVER_ENABLE=1
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLEET_SERVER_SERVICE_TOKEN=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE3MzcwMDk5NzgzODM6YmZXSmFlbjlRa21KTkZNeVVRRF9BUQ
      - FLEET_SERVER_POLICY=fleet-server-policy
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - KIBANA_HOST=http://kibana:5601
      - KIBANA_FLEET_SETUP=true
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "8220:8220"
    volumes:
      - ./data/fleet-server:/usr/share/elastic-agent/data
      - ./certs:/usr/share/elastic-agent/certs
      # - ./certs:/usr/share/kibana/config/certs

  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.10.1
    container_name: elastic-agent
    environment:
      - FLEET_ENROLL=1
      - FLEET_SERVER_INSECURE_HTTP=true
      - FLEET_SERVER_HOST=http://fleet-server:8220
      - FLEET_ENROLLMENT_TOKEN=YWxPUVk1UUJxcDE1TGxQci1lTEw6UHo1M3BjT1JTb0NqYlJDZVNBQXBTQQ==
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - KIBANA_HOST=http://kibana:5601
    depends_on:
      - fleet-server
    ports:
      - "6789:6789"
    volumes:
      - ./data/elastic-agent:/usr/share/elastic-agent/data
      - ./certs:/usr/share/elastic-agent/certs         


volumes:
  es_data:
    driver: local

# networks:
#   default:
#     driver: bridge
